### ISSUE TITLE
[Feature Request] Add support for Next.js

### ISSUE THREAD

**Issue by jferrettiboke** [fern-api/fern#1661]
Hey there! 👋

I've been trying Fern to build a REST API, and I'm a big fan of it. It's been an awesome experience so far! 🌟

I was wondering if there's any plan to add support for Next.js integration in Fern. Next.js is a popular framework for building applications, and having Fern seamlessly integrate with it would be fantastic! It would save us a lot of time and effort in developing APIs and ensuring they are served correctly.

Is this something you have on your roadmap? If not, I'd love to discuss the possibility and contribute to making it happen. Let me know your thoughts!

Thanks a bunch! 🙌

**Comment by zachkirsch** [comment]
Hey @jferrettiboke!

Sorry for the delay. You're right that we don't yet support Next.js for server-side code generation. The main reason we haven't designed for it yet is because of its path-based routing (i.e. the file names / folder structure determine the API). In our other server-side generators, our generated code lives completely separately from the manually-written code, so it's easy to regenerate without overwriting business logic.

That said, something being hard isn't a good enough reason not to built it! Would love to hear more about how you'd want fern to work with Next.js, what code would be generated, etc. I'd love for us to support this and if you want to contribute it, even better!

**Comment by dannysheridan** [comment]
Closing as we don't plan to support additional server-side code generators in the near future
