### ISSUE TITLE
Validate that env variables in generators.yml are present in github workflows

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1879]
If a user has the file `.github/workflows/ci.yml` then any env variable in `generators.yml` should also be present here. It would be nice if `fern check` could validate that this is true.

For example, I added a Node.js SDK generator into `generators.yml`, so my `ci.yml` should change occordingly:

```diff
      - name: Generate SDKs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
+       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by dsinghvi** [comment]
Going to close this -- this is not worth it for a couple reasons: 

1/ It's non trivial to scan all possible github workflows and find the one that is associated with Fern
2/ The CLI will error on running if an env variable isnt provided and the user will update it then. Since this is just one-time setup, that is fine.
