### ISSUE TITLE
Show contributors across all fern repos 

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1903]
It would be nice if all contributors to the generators (go/python/java/typescript) also got acknowledged!

**Comment by aevitas** [comment]
That'd be very nice. I've looked into some of the options we have available:

* There's a specification/app called [all-contributors](https://github.com/all-contributors/app) which supports maintaining a list of contributors outside of code contributions as well, e.g. translations, design, etc. We could use this, but it would entail installing a bot and following its workflows in order to maintain the contributor list over time. 
* There is a [GitHub Action available (or an npm command) to merge all the contributors across repositories](https://github.com/marketplace/actions/merge-all-contributors) under our org into one, which we could then display in our main README.

We're currently using [contrib.rocks](https://github.com/lacolaco/contributors-img) - we could use the image for multiple repositories, but that means you, Zack, Danny and others would appear multiple times.

First one is more thorough, would take up more space in the readme, but overall would be more complete. The latter is a quick solution.

**Comment by dsinghvi** [comment]
Deprioritizing this for now.
