### ISSUE TITLE
[Feature] API Playground

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2562]
### Problem description

As a user, I want to be able to call the API from within the documentation website. `Try it now` is how other docs providers phrase this functionality.

### Why would it be useful?

It would let a user quickly try out the API and make a call.

**Comment by aleksAperans** [comment]
+1 here, for the sayari site, we'd love to have this option. 

**potential acceptance criteria:** 

for the API client, reading the api reference

- have the ability to toggle between pre-set examples and a "try it" sandbox mode

when in "try it" sandbox mode 

- have the ability to select a language (python, node, shell etc...)
- have the ability to enter in my authorization credentials (bearer token for Sayari)
- have the ability to enter query parameters and body parameters 
- receive validation if a value entered into a query param or body param is invalid 
- see the request code snippet update dynamically with values I enter in the query param or body param, so that I can copy
- see the response code snippet accurately reflect my inputs on the payload, and subsequently copy the payload.

As a developer utilizing fern I would like the ability to 
- specify which languages I want to surface to my clients I may only want to leave the impression that its recommended to use (curl, python, go and node) for example.
- specify if the default request / response is set to an pre-filled example or to "try it" mode.
- have the ability to disable "try it" mode. This should not be forced.
- provide and seed default "dummy" auth credentials for potential clients to experiment. 
- nice to have, ability to retrieve logs of what clients are entering into "try it" mode.

some inspiration: 

1. readme.com (notion)
![aa 06 01](https://github.com/fern-api/fern/assets/139813505/3f60c2d1-a25e-4edd-bfa6-0319a7cad4d9)



2. redoc.ly
![aa 06 01](https://github.com/fern-api/fern/assets/139813505/8b28a30f-d7cc-4e19-a57d-4ebdc5a1ecfd)

**Comment by dannysheridan** [comment]
This feature is in development! We expect to have a version in production later this quarter. Stay tuned! Thanks for opening this feature request @aleksAperans !
