### ISSUE TITLE
[Bug] Side Nav not updating when link is followed to different page

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern#2644]
### Describe the bug
When a link is clicked and redirects to a different page, the side-nav still shows the original page selected even though the user is now on a different page.

### To reproduce
1. Go to these preview docs: https://sayari-analytics-preview-8d472466-ecb5-423d-88b4-fcc2ee310a0a.docs.buildwithfern.com/
2. Navigate to "Sayari Library" -> "Ontology" -> "Entities"
3. Click attributes link "additional_information"
4. Done, you are now on the attributes page, but entities is still selected in the side nav

### Expected behavior
The side nav should reflect the page currently being displayed

### Screenshots
<img width="1455" alt="Screenshot 2024-01-17 at 10 12 39 AM" src="https://github.com/fern-api/fern/assets/72822263/3b44935a-3dc6-4dd0-a986-3bfde1b61be2">

### Version
"0.16.33"

### Additional context
N/A

**Comment by minaelee** [comment]
I find that this **only** happens when the link is to a named anchor or `id` on a page. That is, when it's a link like `/something#heading_id`. Otherwise, the side nav updates as expected.

You can see an example of this on Fern's own docs. Go to https://docs.buildwithfern.com/generate-sd-ks/generators/type-script-browser-sdk and scroll to the bottom. Click the link there to /generate-sd-ks/generators/type-script-node-js-sdk#configuration-options and see that the side nav does not switch to the TypeScript NodeJS SDK.

**Comment by dannysheridan** [comment]
Bug squashed between Feb and now!
