### ISSUE TITLE
Investigate the scope of fixing the auto-generated Cosmos SDK OpenAPI spec 

### ISSUE THREAD

**Issue by Olshansk** [fern-api/fern#3023]
### Problem description

The auto-generated OpenAPI spec in the Cosmos SDK is bug-prone per the description [here](https://github.com/cosmos/cosmos-sdk/issues/19268).

This feature request is an ask of the fern ecosystem, with experience and expertise in this field, to look into the amount of effort it would be to enable native fern integration with the gRPC services in the Cosmos SDK. The actual work can be tracked in a followup ticket.

### Why would it be useful?

The [Cosmos SDK](https://v1.cosmos.network/sdk) is the leading framework for building custom blockchains. Lots of small teams rebuilt SDK tooling which is Fern's core value proposition.

### Describe the solution (optional)

The fern SDK hooks into the gRPC services and related protobufs to generate language specific SDKs.

### Additional context

I have personally done a deep dive trying to get this to work via the OpenAPI spec resulting in these two issues: https://github.com/fern-api/fern/issues?q=olshansk

The discussion [here](https://github.com/cosmos/cosmos-sdk/issues/19268) points to the fact that we should potentially bypass the OpenAPI spec and reference the gRPC service and related protobufs directly.

**Comment by amckinney** [comment]
Following up with the context from https://github.com/fern-api/fern/issues/2813 -

We recently did some investigation into this and found that Google's [`protoc-gen-openapi`](https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi) is better suited for mapping `.proto` to OpenAPI. Please give that a shot and let us know how it goes - you might see that the original issue with the Cosmos API is resolved.

With that said, we'll still need to build in proper support for calling the services defined in your `.proto` files from Fern SDKs (i.e. supporting gRPC instead of REST), but this will at least show you what the Fern-generated SDK will feel like in the meantime. If you're happy with the result, we'd be happy to work with you on making this happen!

**Comment by dannysheridan** [comment]
@amckinney mind updating this issue? After the announcement of gRPC and REST out of a single SDK for Pinecone, I believe there are developments here that users can take advantage of! 

https://buildwithfern.com/blog/pinecone

**Comment by amckinney** [comment]
Thanks @dannysheridan - 

@Olshansk as you can see from the blog post above, we recently rolled out gRPC support in C# and it's currently being used in the [official Pinecone SDK](https://github.com/pinecone-io/pinecone-dotnet-client).

Is this feature still something you're interested in? It'd be interesting to see if the C# solution works well for your use case. We plan to roll out support in the other languages, but we have a few other higher priority things currently in flight.

**Comment by amckinney** [comment]
For our own issue tracking, I'll go ahead and close this one for now, but feel free to reopen as needed!
