### ISSUE TITLE
[Bug] PackageNotFoundError when getting the version of the current package

### ISSUE THREAD

**Issue by maxdeichmann** [fern-api/fern#3319]
Reference: https://github.com/langfuse/langfuse-python/blob/63c0fa497dc04d295363158b0ff1be382edb3f10/langfuse/api/version.py#L3

In our Langfuse Python SDK, we upgraded to Python Generator. 1.0.0. Unfortunately, the line `__version__ = metadata.version("__package__")` fails on runtime with the following exception:
```
____________________________________________________________________ ERROR collecting tests/test_core_sdk.py _____________________________________________________________________
ImportError while importing test module '/Users/maximiliandeichmann/development/github.com/langfuse/langfuse-python/tests/test_core_sdk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../Library/Caches/pypoetry/virtualenvs/langfuse-3vNqg5EL-py3.9/lib/python3.9/site-packages/_pytest/python.py:520: in importtestmodule
    mod = import_path(
../../../../Library/Caches/pypoetry/virtualenvs/langfuse-3vNqg5EL-py3.9/lib/python3.9/site-packages/_pytest/pathlib.py:584: in import_path
    importlib.import_module(module_name)
../../../../.pyenv/versions/3.9.1/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
../../../../Library/Caches/pypoetry/virtualenvs/langfuse-3vNqg5EL-py3.9/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests/test_core_sdk.py:6: in <module>
    from langfuse.utils import _get_timestamp
langfuse/__init__.py:4: in <module>
    from .client import Langfuse  # noqa
langfuse/client.py:10: in <module>
    from langfuse.api.resources.ingestion.types.create_event_body import CreateEventBody
langfuse/api/__init__.py:99: in <module>
    from .version import __version__
langfuse/api/version.py:3: in <module>
    __version__ = metadata.version("__package__")
../../../../.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py:551: in version
    return distribution(distribution_name).version
../../../../.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py:524: in distribution
    return Distribution.from_name(distribution_name)
../../../../.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py:187: in from_name
    raise PackageNotFoundError(name)
E   importlib.metadata.PackageNotFoundError: __package__
```

Reproduce:
- Fork our SDK and the branch
- Change the 'langfuse' to '__package__'
- Execute tests as described in https://github.com/langfuse/langfuse-python/blob/63c0fa497dc04d295363158b0ff1be382edb3f10/CONTRIBUTING.md#L24

**Comment by armandobelardo** [comment]
@maxdeichmann could you share your Fern configuration (e.g. the contents of generators.yml as well as the version within fern.config.json)? We should only default to this if we cannot determine the package being created

**Comment by maxdeichmann** [comment]
Fern config: https://github.com/langfuse/langfuse/blob/main/fern/fern.config.json
Python Generator: https://github.com/langfuse/langfuse/blob/main/fern/apis/server/generators.yml#L13

**Comment by maxdeichmann** [comment]
Thanks for looking into this!

**Comment by armandobelardo** [comment]
Ah I see! Yeah this is confusing!

Since you do local publishing and we don't control the pyproject.toml there (or the other project files), we don't know the project name and so we use "__project__" to try to pull it in from elsewhere, and you can always manually update it and add the file to your `.fernignore` if necessary (structured similar to a .gitignore, Fern won't touch files listed there on regeneration).

I'll go ahead and remove this from local publishing!

@maxdeichmann could I ask why you're not leveraging github output mode to PR to your repo automatically? https://buildwithfern.com/learn/sdks/guides/github-bot#pull-request-mode

**Comment by maxdeichmann** [comment]
@armandobelardo thanks a lot for the hint to .fernignore. Can you point me to docs on how to use it to exclude https://github.com/langfuse/langfuse-python/blob/63c0fa497dc04d295363158b0ff1be382edb3f10/langfuse/api/version.py
?
I cannot find it in the docs.

I think we do not use the github feature as it did not exist when we set up fern initially.

**Comment by armandobelardo** [comment]
It's not a well documented feature since there are some downsides! So we tend to not promote it and only suggest it when necessary
Since you're running local generation it's also a touch less relevant anyway

I've released a fix for this in version 1.1.0-rc1 here's the change: https://github.com/fern-api/fern/pull/3320
Note that if you are not on 1.0.0, there are breaking configuration changes, to continue with the existing configuration you have today, you must follow the config in the changelog: https://github.com/fern-api/fern/blob/main/generators/python/sdk/CHANGELOG.md#100---2024-04-02

**Comment by maxdeichmann** [comment]
Hi, so i assume i dont have to do anything once the fix is live?

**Comment by armandobelardo** [comment]
That's correct, you can upgrade your generator now actually! It will remove the bad files, and you should be set!
