### ISSUE TITLE
Service-level header doesn't populate in the Node SDK

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#838]
The TypeScript SDK generator is not picking up the idempotency key, which is passed as a header on the service-level.

**Comment by dsinghvi** [comment]
This should be resolved with release 0.0.6 of [primer-node](https://github.com/fern-primer/primer-node/commits/main) . Fixing involved: 
  - Upgrading Primer's TypeScript SDK Generator ([PR](https://github.com/fern-primer/primer-api/pull/2))
  - Overriding the codegen name for `X-Idempotency-Key` to be `idempotencyKey` instead of `xIdempotencyKey` ([PR](https://github.com/fern-primer/primer-api/pull/3))
